services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\FieldTypeRichText\REST\FieldTypeProcessor\RichTextProcessor:
        arguments:
            - '@ibexa.richtext.converter.edit.xhtml5'
        tags:
            - { name: ibexa.rest.field_type.processor, alias: ezrichtext }
