services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Bundle\FieldTypeRichText\Templating\Twig\Extension\RichTextConverterExtension:
        arguments:
            $richTextOutputConverter: '@ibexa.richtext.converter.output.xhtml5'
            $richTextEditConverter: '@ibexa.richtext.converter.edit.xhtml5'

    Ibexa\Bundle\FieldTypeRichText\Templating\Twig\Extension\YoutubeIdExtractorExtension: ~

    Ibexa\Bundle\FieldTypeRichText\Templating\Twig\Extension\RichTextConfigurationExtension: ~
